import { useEffect, useState } from "react";
import { CATALOG, type LocaleTag } from "./app-locales";
export type { LocaleTag };

/*
 * Minimal i18n for user-facing controls. Standards-shaped: BCP 47 tags,
 * navigator.language detection with nearest-tag matching, explicit choice
 * persisted in localStorage, t(key) drop-in compatible with i18next.
 * Catalogs generated by localize/build.py (single source of truth).
 */
const STORAGE_KEY = "i18n-locale";
export const LOCALE_NAMES: Record<LocaleTag, string> = {
	en: "English", es: "Español", ja: "日本語", "zh-Hans": "简体中文",
	"zh-Hant": "繁體中文", yue: "粵語", hi: "हिन्दी", ar: "العربية", ko: "한국어",
};

const listeners = new Set<() => void>();
let current: LocaleTag = detect();
syncDom(current);

export function detect(): LocaleTag {
	const param = new URLSearchParams(window.location.search).get("lang");
	if (param && param in CATALOG) return param as LocaleTag;
	try {
		const saved = localStorage.getItem(STORAGE_KEY);
		if (saved && saved in CATALOG) return saved as LocaleTag;
	} catch { /* private mode */ }
	const lang = navigator.language || "en";
	const primary = lang.split("-")[0];
	if (lang in CATALOG) return lang as LocaleTag;
	if (primary === "zh") return (lang.includes("Hant") ? "zh-Hant" : "zh-Hans") as LocaleTag;
	if (primary in CATALOG) return primary as LocaleTag;
	return "en";
}

export function syncDom(tag: LocaleTag): void {
	document.documentElement.lang = tag;
	document.documentElement.dir = tag === "ar" ? "rtl" : "ltr";
}

export function setLocale(tag: LocaleTag): void {
	current = tag;
	try { localStorage.setItem(STORAGE_KEY, tag); } catch { /* private mode */ }
	syncDom(tag);
	listeners.forEach((fn) => fn());
}

export function t(key: string): string {
	return CATALOG[current][key] ?? CATALOG.en[key] ?? key;
}

/** Re-render the component when the locale changes. */
export function useLocale(): { locale: LocaleTag; setLocale: (t: LocaleTag) => void } {
	const [, force] = useState(0);
	useEffect(() => {
		const fn = () => force((n) => n + 1);
		listeners.add(fn);
		return () => { listeners.delete(fn); };
	}, []);
	return { locale: current, setLocale };
}
